version: "3.9"

services:
  apphub-server-backend:
    image: apphub:latest
    build: .
    pull_policy: never
    entrypoint: ["node", "dist/apps/backend/main.js"]
    ports:
      - "3000:3000"

  apphub-server-frontend:
    image: apphub:latest
    build: .
    pull_policy: never
    entrypoint: ["node", "dist/apps/frontend/main.js"]
    ports:
      - "3001:3001"
