version: "3.9"
name: apphub
services:
  apphub-server-backend:
    image: apphub-dev:latest
    build:
      context: .
      target: development
    pull_policy: never
    command: sh -c "npm install && npm run start:dev backend"
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - DEBUG=1

  apphub-server-frontend:
    image: apphub-dev:latest
    build:
      context: .
      target: development
    pull_policy: never
    command: sh -c "npm install && npm run start:dev frontend"
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    environment:
      - DEBUG=1

  apphub-web:
    image: apphub-dev:latest
    build:
      context: .
      target: development
    pull_policy: never
    command: sh -c "npm install && ng serve --host=0.0.0.0 --disable-host-check=true"
    ports:
      - "4200:4200"
    depends_on:
      - apphub-server-backend
    volumes:
      - ./web:/usr/src/app
